language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
cache: bundler
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 'lts/*'
  - nvm use 'lts/*'
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
install: "bin/setup"
script: "bin/ci-run"
