name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  push:
    permissions:
      contents: write
      id-token: write
    if: github.repository == 'ackama/lighthouse-matchers'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - uses: rubygems/release-gem@v1
